""" This file contains dict values that is used while printing defects """

customDict = dict(
	CONTAINS_HASHTAG_WITH_INTEGER = "# ALONGSIDE INTEGERS",   #0
	CONTAINS_HASHTAG_WITH_STRING = "# ALONGSIDE STRINGS",   #1
	DECIMAL_VALUE = "DECIMAL VALUE",   #2
	DOT_BUT_NOT_EMAIL_OR_WEBSITE = "DOT (but not email or website)",   #3
	DUPLICATE_EMAIL = "DUPLICATE EMAIL",   #4
	EMAIL = "AN EMAIL",   #5
	EMPTY = "AN EMPTY ENTRY",   #6
	FOUR_DIGIT_ZIPCODE = "FOUR DIGIT ZIP CODE",   #7
	HYPHEN = "A HYPHEN",   #8
	IMPROPER_DECIMAL = "AN IMPROPER DECIMAL INTEGER",   #9
	IMPROPER_INTEGER = "AN IMPROPER INTEGER",   #10
	INTEGER = "AN INTEGER",   #11
	INTEGER_BUT_NOT_ZIPCODE  = "PURE INTEGER (but not zipcode)",   #12
	INTEGER_ONLY = "ONLY INTEGER",   #13
	INTEGER_WITH_PARANTHESES = "INTEGER WITH PARANTHESES",   #14
	MORE_INTEGER_THAN_STRING = "INTEGERS DOMINATE STRING",   #15
	MORE_STRING_THAN_INTEGER = "STRING DOMINATES INTEGER",   #16
	NON_US_STATE_CODE = "NON US STATE CODE",   #17
	NO_DOTS = "NO DOTS",   #18
	PARANTHESES_WITH_STRING = "STRING_WITH_PARANTHESES", #19
	POSSIBLE_ZIPCODE = "POSSIBLE ZIPCODE",   #20
	PURE_STRING = "A PURE STRING",   #21
	SPACE = "A SPACE",   #22
	SPECIAL_CHARACTER = "A SPECIAL CHARACTER",   #23
	SPECIAL_CHARACTER_FOR_PHONE = "A SPECIAL CHARACTER (unlikely for phone)",   #24
	SPECIAL_CHARACTER_FOR_WEBSITE = "A SPECIAL CHARACTER (unlikely for website)",   #25
	STRING = "A STRING ENTRY",   #26
	STRING_WITHOUT_HYPHEN = "A STRING WITHOUT HYPHEN",   #27
	STRING_WITH_INTEGER_AND_SPACES = "A STRING WITH INTEGER AND SPACES",   #28
	UPPERCASE = "AN UPPERCASE", #	29
	US_STATE_CODE = "US STATE CODE",   #30
	US_STATE_CODE_IN_LOWERCASE = "US STATE CODE IN LOWERCASE",   #31
	WEBSITE = "WEBSITE",   #32
	ZIPCODE_WITH_HYPHEN = "ZIP CODE WITH HYPHEN",   #33
	at_the_rate_BUT_NOT_EMAIL_ENTRY = "@ BUT NOT EMAIL",   #34
	at_the_rate_WITH_DECIMAL_INTEGERS = "@ WITH DECIMAL INTEGERS",   #35
	at_the_rate_WITH_INTEGERS = "@ WITH INTEGERS", #36
	email_with_improper_format = "WRONGLY FORMATTED EMAIL", #37	
	improper_symbols = "IMPROPER SYMBOLS", #38
	zipcode_that_does_not_match_with_state_code = "MISMATCHED ZIPCODE"  #39
	
)
sortedDict = [(key,customDict[key]) for key in sorted(customDict)]